import { createClient } from '@/lib/supabase/server'

// Notification queue reads (migration 023). Queue-only: rows are generated by
// generate_renewal_reminders(); actual delivery (email/WhatsApp/SMS) is a future
// step. RLS (notifications_select_scoped) lets a user read reminders they receive
// or that are tied to a policy/lead in their scope.

export type RenewalNotification = {
  id: string
  status: string
  channel: string
  policy_id: string | null
  scheduled_at: string
  payload: Record<string, unknown> | null
}

/** Pending renewal reminders visible to the current user (RLS-scoped). */
export async function listPendingRenewalReminders(): Promise<RenewalNotification[]> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('notifications')
    .select('id, status, channel, policy_id, scheduled_at, payload')
    .eq('type', 'policy_renewal_reminder')
    .eq('status', 'pending')
    .order('scheduled_at', { ascending: true })
  if (error) return []
  return (data ?? []) as RenewalNotification[]
}
